เพิ่มการทำงานนี้เข้าไปหน่อย 
หลังจากจบขั้นตอนlogin 
ให้มันทำขั้นconfigเพิ่ม 
โดยนำขั้นตอนboxมาใส่ก่อน เราเปิด box = 1ในconfigนะค่อยทำงาน
หลังจากนั้น ให้มันทำงาน maxgacha = 1 ถ้าเราเเปิด 
โดยขั้นตอน 
maxgacha1  -> "แวะหา disk-full1 5วิ ไม่เจอข้าม แต่ถ้าเจอให้มันกด disk-full2 -> disk-full3 10s" maxgacha2 -> maxgacha3 ->ให้มันหา maxgacha3 15s 
แต่ถ้าเจอ "ให้มันทำงาน maxgacha-step1" แล้วให้มันหา ด้วย 
ITEM_GET_MAP = ด้วยหลักการตรงนี้มันจะวน maxgacha3 -> maxgacha-step1 หา ITEM_GET_MAP ไปเรื่อยๆ จนกว่าจะไม่เจอ maxgacha3 15s
ิอย่าพึ่งจบการทำงานนะ ให้มันจดจำชื่อที่มันmathได้ แล้วไปstepต่อไปเลย 

 ถ้าไม่เจอข้ามไป maxgacha4 15s ให้มันไปทำงาน #step-ruby 119
หลังจากกด maxgacha4 แล้วให้มันเพิ่มเติมตรงนี้5วิ หาfix-space1 ถ้าเจอให้มันทำงานก่อน fix-space1 -> fix-space6 แล้วค่อบทำงานตามปกติ 
#step-ruby 119 
แล้วให้มันทำขั้นตอน หลังจากกด maxgacha4 -> "แวะหา disk-full1 5วิ ไม่เจอข้าม แต่ถ้าเจอให้มันกด disk-full2 -> disk-full3 10s" -> maxgacha5 -> แล้วกด maxgacha5ไปเรื่อยๆจนกว่าไม่เจอ 5วิ
ให้มันแวะหา ITEM_GET_MAP = {  ให้มันจดจำชื่อที่มันmathได้ แล้วไปstepต่อไปเลย 


เสร็จแล้วให้มัน draw-agin -> แวะหา "แวะหา disk-full1 5วิ ไม่เจอข้าม แต่ถ้าเจอให้มันกด disk-full2 -> disk-full3 10s" ->  เสร็จแล้วถ้ามันยังเจอ 
draw-agin ให้มันกดอีกรอบ เพิ่มเงือนไขdraw-aginถ้ามันเจอ stop-step2 แล้วให้มันbreak ออกมาโดยกด cancel-step2 -> cancel-step2v1 
แล้วไปทำงานที่ get-random25 เลย

แต่ถ้าไม่เจอ stop-step2ให้มันทำงานปกติ
แล้วให้มันกด ok-get ไปเรื่อยๆจนกว่าไม่เจอ 5 วิ 
แล้วให้มันกด draw-agin อีกรอบถ้ามันเจอให้มันกด แตถ้ามันเจอ stop-ruby ให้มันกด cancel1 -> cencel2 แล้วทำงาน 

step2 
ทำงาน get-random25 -> "แวะหา "แวะหา disk-full1 5วิ ไม่เจอข้าม แต่ถ้าเจอให้มันกด disk-full2 -> disk-full3 10s" ->  

เสร็จแล้วทำงาน ok-getstep2 -> ไปเรื่อยๆจนกว่าจะเจอ stop-step2 แล้ว break ออกมาโดยกด cancel-step2 -> cancel-step2v1 -> cancel-step2v2
-> cancel-step2v3 

อ่าหลังจากจบการทำงานแล้วส่งไฟล์ออกมาเลยชื่อเดิม 
ตามจำนวนที่เจอในขั้นตอนmax-gacha ไปเลย +headking+[CRLLL8384]+.zip 


จะจบการทำงานได้ก็ต่อเมื่อทำงานถึง step2 นะที่เหลือห้ามclearapp ก่อน ให้มันเรียงลำดับการทำงานตามนี้