เพิ่มการทำงานนี้ให้หน่อย

ให้มันใช้วิธีเดียวกันในการคลิกรูปภาพและเชื่อมadb มาจากไฟล์ 
C:\Users\Administrator\Downloads\pes-new\pes

หลักการทำงานก็คือ ก่อนstartให้มันปิด root ได้ไหม ใช้คำสั่งอะไรก็ได้ในการปิดrootก่อน start packet
start packet เกม cookie run 
/data/data/com.devsisters.crg 

กดรูปภาพ -> play1 ->เสร็จแล้วกดตำแหน่ง 419 282 -> 
เสร็จแล้วกดรูปplay2 -> play3 -> play4 -> play5 -> play6 
มี timeout 15s -> แค่play6 นะ -> เสร็จแล้วกด play7 -> play8 
กดเรื่อยๆจนถึง play 11 แล้วทำการสร้างไฟล์ config custom ชื่อเพื่อพิมพ์
เช่น ozx แล้วให้มันกรอกลงแล้วกด enter แล้วกด play12 -> 
เสร็จแล้วให้มัน event-back timeout 10s ไปเรื่อยๆจนกว่าจะไม่เจอ event-back ครบ 8วิ
ค่อยไปหารูป git-item timeout 10s เหมือนกันทำงานเหมือน event-back -> 
ทำงานเหมือน ok-gifitem timeout 10s เลย event-backเลย 

เสร็จแล้ววนอีกรอบ ตั้งแต่evnet-back จนถึง ok-gifitem เอาง่ายๆทำงาน2รอบ

เสร็จแล้วทำงาน
#รับของ
box1-> box2 -> box3 -> box4 -> box5 


#สุ่มของ get-item
หลักการทำงานส่วนี้ก็คือ 
ทำงานแค่รอบเดียว item1 -> item2 

อันนี้ให้มันวนกดไปเรือยๆจนกว่าเจอ item3 -> item4  end-item แล้ว breakออกมา
เออลืมบอกให้มันหารูปmath ที่มันตรงกับ 
math รูปในโฟเดอร์
\img\item-get
ว่าเจอ ในconfig นะ ทำไฟล์เก็บไว้แบบนี้แล้วเอามาmath
item1.bmp = backpack  
item2.bmp = headking
item3.bmp = banana

กรณีที่มันเจอ ให้มัน จดจำค่าที่เจอไว้นะ เช่นเจอ item.bmp = backpack ให้มันจดจำไว้ว่าเจอ 
อย่าพึ่งทำไรให้มันไปทำงานget-petให้มันจบก่อน ถ้าเจอมากกว่า2รูปก็ให้มันจำไว้นะ จะเก็บชื่อไว้รอทำขั้นตอนส่งไฟล์ออกไป

เมื่อกด itemแล้วเจอ end-item ให้มันทำงาน cancel -> confirm-item -> back1 -> back2 

#แล้วทำงาน get-petต่อเลย
กด pet1 -> pet2 ทำงานแค่1รอบนะ 
ให้มันหารูปmath ที่มันตรงกับ 
math รูปในโฟเดอร์
\img\pet-get 
ว่าเจอ ในconfig นะ ทำไฟล์เก็บไว้แบบนี้แล้วเอามาmath
pet-item.bmp =   trader 


pet3 -> pet4 ให้มันการทำงานไปเรื่อยๆจนกว่า คลิก pet3 แล้วเจอ end-pet แล้ว break ออกมา
อีกกรณ์ก็คือถ้าเจอ pet-item ให้มัน จบการทำงานแล้วจดชื่อไฟล์ออกมาเลย clear app 

clear app แล้วทำงานการทำการลบไฟล์ 
แล้วเปิด root ให้มัน ก่อนทำการพวกนี้ 
ยกตัวอย่างเวลาเจอ ต้องสร้างไฟล์ .zip 
path แรก 
/data/data/com.devsisters.crg/shared_prefs 
ไปคัดลองมาไฟล์ที่ต้องคิดลอก
Cocos2dxPrefsFile.xml
com.devsisters.crg.v2.playerprefs.xml
com.devsisters.plugin.appInstalledId.pref.xml
com.devsisters.plugin.devsisterscontent.prefs.xml
แล้วเข้า path นี้ไปcopy มา 
/data/data/com.devsisters.crg/files
.C80C5535E9E69661F4C5FCFEC98D662D

แล้วทำการzipมาพวกนี้รวมกันมาเก็บใว้ในbackup 
กรณีจดชื่อไฟล์จะเป็นแบบนี้ headking+trader.zip แต่ถ้าเจอ แค่ headking.zip หรือ trader.zip หรือ headking+banana+trader.zip 
ถ้าเจอมากเจอมากกว่านี้ก็นำมา+กันได้เลย 
แต่ถ้าเจอแค่ banana เดี่ยวๆไม่ต้องจดมานะ ถ้าสุ่มทั้ง2ขั้นตอนแล้วทั้ง get-pet กับ get-item แล้วไม่เจอ 
ทำให้มันcustomในconfigก็ได้ เงือนไข ใส่ข้างหลังที่เราต้องการว่า ture 
backpack ด้วยทำงานเหมือน banana ถ้าเจอเดี่ยวไม่ต้องจดมา 

แต่ถ้าเจอ banana + trader ให้มัน จดออกมาด้วย banana+trader.zip 
or backpack + trader ให้มันจดออกมาด้วย backpack+trader.zip 

หลังจากส่งออกมา ให้มันลบก่อนเริ่มการทำงานใหม่ลบไฟล์
แล้วเปิด root ให้มัน ก่อนทำการพวกนี้ 
/data/data/com.devsisters.crg/shared_prefs 
Cocos2dxPrefsFile.xml
com.devsisters.crg.v2.playerprefs.xml
com.devsisters.plugin.appInstalledId.pref.xml
com.devsisters.plugin.devsisterscontent.prefs.xml
path 
/data/data/com.devsisters.crg/files
.C80C5535E9E69661F4C5FCFEC98D662D

แล้วไปเริ่มขั้นตอนใหม่ได้เลย 

กรณีถ้าสุ่มทั้ง2ขั้นตอนไม่เจออะไรเลยให้มัน ลบไฟล์
แล้วเปิด root ให้มัน ก่อนทำการพวกนี้ 
/data/data/com.devsisters.crg/shared_prefs 
Cocos2dxPrefsFile.xml
com.devsisters.crg.v2.playerprefs.xml
com.devsisters.plugin.appInstalledId.pref.xml
com.devsisters.plugin.devsisterscontent.prefs.xml
path 
/data/data/com.devsisters.crg/files
.C80C5535E9E69661F4C5FCFEC98D662D
แล้วเริ่มเริ่ม start เริ่มขั้นตอนใหม่ได้เลยตั้งแต่ start packet 