
login-new = 1 


step1 
ลบไฟล์ 
SHARED_PREFS_DIR = "/data/data/com.devsisters.crg/shared_prefs"
SHARED_PREFS_FILES = [
    "Cocos2dxPrefsFile.xml",
    "com.devsisters.crg.v2.playerprefs.xml",
    "com.devsisters.plugin.appInstalledId.pref.xml",
    "com.devsisters.plugin.devsisterscontent.prefs.xml",

หลังจากstartgame ให้มันเอาขั้นตอน 

#step2 
play1 -> กดตำแหน่งมาด้วย play2 -> play3 -> play4 ละ ตรงนี้ทำขั้นตอนนี้ 


กด newlogin ก่อนแล้วค่อยกด
loginnew1 -> 
ให้มันจำชื่อไฟล์เดิมมา.txt ไว้ก่อนรอส่งออก

หลังจากนั้นให้มันดึงค่ามาจากไฟล์ โดยรูปแบบไฟล์จะเป็นแบบนี้
-RBJCC1696@gmail.com/moxW2PC71z
เราจะนำ RBJCC1696@gmail.com แบบนี้มากรอก แล้วกด -> loginnew2 

กด loginnew3 
แล้วดึงค่ามา /moxW2PC71z แบบนี้มากรอกต่อในช่อง แล้วกด -> loginnew4 


เสร็จแล้ว 
fixplay1 -> fixplay2 -> fixplay3 -> fixplay4 

เสร็จแล้ว
รอ check-pointevent.bmp → delay 8 วิ ให้จอนิ่ง
event loop (event-back/git-item/ok-gifitem...) — เจอ stopeventloop ค้าง 5 วิ ถึงหยุด


แล้วจบการทำงานlogin-new1 เลย แล้วก็ทำงานตามสเต็ปเดิมเลย ถ้าไม่ได้เปิดอะไรต่อก็ให้มันจบการทำงาน แล้วส่งไฟล์
ออกมา login-success แล้วก็ไปเข้าสเต็ปใหม่ได้เลย ชื่อเดิม.txt แล้วมีข้อมูลชุดเดิมข้างในด้วย