[127.0.0.1:16512] === PLAY-LV5 ===
[127.0.0.1:16512] คลิก play1.bmp ที่ (712,482)
[127.0.0.1:16512] คลิก play2.bmp ที่ (399,333)
[127.0.0.1:16512] กด play3.bmp ซ้ำ 10 ครั้ง ที่ (751,219)
[127.0.0.1:16512] คลิก play4.bmp ที่ (170,450)
[127.0.0.1:16512] กด play5.bmp ซ้ำ 10 ครั้ง ที่ (688,220)
[127.0.0.1:16512] คลิก play6.bmp ที่ (675,461)



[127.0.0.1:16512] คลิก play7.bmp ที่ (574,181)


[127.0.0.1:16512] รอ wait-step1 ค้างครบ 5s...


หลังจากจบขั้นตอนevent loop 
play-lv5 = 1 
ให้มันทำขั้นตอน 
pathรูป /img/play-lv5/*

#step start 
กดรูป -> play1 -> play2 -> play3 แล้วกดซ้ำๆ play3 10ครั้ง 

#loop buy item
แล้วกด -> play4 -> play5 แล้วกดซ้ำๆ play5 10ครั้ง -> play6 -> play7 -> play8 แล้วรอเจอwait-step1 ค้าง5วิ 
แล้วค่อยกด wait-stepok1 ให้มันกดซ้ำๆจนกว่าจะหายไป wait-stepok1 

#loop play -> withberak lv-5 img 
-> playloop1 -> playloop2 5s ไม่เจอข้าม -> playloop3 -> playloop4 -> playloop5 
-> แล้วเช็คหาถ้าเจอ lv-check 3s แล้วให้มันเหา lv-5.bmp ก่อน แล้วค่อยกด playloop6 5s ไม่เจอข้าม แต่ถ้ามันเจอ playloop6 ให้มันเช็คหา lv-5.bmp 
ถ้าเจอ ให้มัน กด lv-5ok1 -> lv-5ok2 -> lv-5ok3 แล้วให้มันทำงาน 
    "link_devid": 1, -> แต่ให้มันส่งไฟล์ออกมาเหมือนกันนะแต่จะเป็นรูปแบบไฟล์

lv-5norandom-[อันนี้เลขuidให้มันดึงมาใส่].txt

ถ้าไม่เจอ playloop6 or ไม่เจอ lv-5.bmp ให้มันกด 
 -> playloop7 5s ไม่เจอข้าม

ทีนี้วนกลับไป playloop1 ใหม่อีกรอบๆเรื่อยๆจนกว่าจะเจอ 